/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.NlToSql.ui.internal.NlToSqlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NlToSqlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(NlToSqlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		NlToSqlActivator activator = NlToSqlActivator.getInstance();
		return activator != null ? activator.getInjector(NlToSqlActivator.UK_AC_KCL_INF_NLTOSQL) : null;
	}

}
