/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.parser.antlr.internal.InternalNlToSqlParser;
import uk.ac.kcl.inf.services.NlToSqlGrammarAccess;

public class NlToSqlParser extends AbstractAntlrParser {

	@Inject
	private NlToSqlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNlToSqlParser createParser(XtextTokenStream stream) {
		return new InternalNlToSqlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AccountingSpeech";
	}

	public NlToSqlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NlToSqlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
