/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparison</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Comparison#getLeftHandSide <em>Left Hand Side</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Comparison#getOperator <em>Operator</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Comparison#getRightHandSide <em>Right Hand Side</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getComparison()
 * @model
 * @generated
 */
public interface Comparison extends LogicExpressions
{
  /**
   * Returns the value of the '<em><b>Left Hand Side</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Hand Side</em>' reference.
   * @see #setLeftHandSide(Column)
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getComparison_LeftHandSide()
   * @model
   * @generated
   */
  Column getLeftHandSide();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nlToSql.Comparison#getLeftHandSide <em>Left Hand Side</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Hand Side</em>' reference.
   * @see #getLeftHandSide()
   * @generated
   */
  void setLeftHandSide(Column value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.nlToSql.ComparisonOperatorString}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see uk.ac.kcl.inf.nlToSql.ComparisonOperatorString
   * @see #setOperator(ComparisonOperatorString)
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getComparison_Operator()
   * @model
   * @generated
   */
  ComparisonOperatorString getOperator();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nlToSql.Comparison#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see uk.ac.kcl.inf.nlToSql.ComparisonOperatorString
   * @see #getOperator()
   * @generated
   */
  void setOperator(ComparisonOperatorString value);

  /**
   * Returns the value of the '<em><b>Right Hand Side</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Hand Side</em>' attribute.
   * @see #setRightHandSide(String)
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getComparison_RightHandSide()
   * @model
   * @generated
   */
  String getRightHandSide();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nlToSql.Comparison#getRightHandSide <em>Right Hand Side</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Hand Side</em>' attribute.
   * @see #getRightHandSide()
   * @generated
   */
  void setRightHandSide(String value);

} // Comparison
