/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Condition#getExpression <em>Expression</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Condition#getLogicOperator <em>Logic Operator</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Comparison)
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition_Expression()
   * @model containment="true"
   * @generated
   */
  Comparison getExpression();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nlToSql.Condition#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Comparison value);

  /**
   * Returns the value of the '<em><b>Logic Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Operator</em>' attribute.
   * @see #setLogicOperator(String)
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition_LogicOperator()
   * @model
   * @generated
   */
  String getLogicOperator();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nlToSql.Condition#getLogicOperator <em>Logic Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic Operator</em>' attribute.
   * @see #getLogicOperator()
   * @generated
   */
  void setLogicOperator(String value);

} // Condition
