/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Condition#getLeft <em>Left</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Condition#getLogicOperator <em>Logic Operator</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.nlToSql.Condition#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends LogicExpressions
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(LogicExpressions)
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition_Left()
   * @model containment="true"
   * @generated
   */
  LogicExpressions getLeft();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.nlToSql.Condition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(LogicExpressions value);

  /**
   * Returns the value of the '<em><b>Logic Operator</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic Operator</em>' attribute list.
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition_LogicOperator()
   * @model unique="false"
   * @generated
   */
  EList<String> getLogicOperator();

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.nlToSql.Comparison}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getCondition_Right()
   * @model containment="true"
   * @generated
   */
  EList<Comparison> getRight();

} // Condition
