/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delete Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getDeleteStatement()
 * @model
 * @generated
 */
public interface DeleteStatement extends Statement
{
} // DeleteStatement
