/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlFactory
 * @model kind="package"
 * @generated
 */
public interface NlToSqlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "nlToSql";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/NlToSql";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "nlToSql";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NlToSqlPackage eINSTANCE = uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.AccountingSpeechImpl <em>Accounting Speech</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.AccountingSpeechImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getAccountingSpeech()
   * @generated
   */
  int ACCOUNTING_SPEECH = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCOUNTING_SPEECH__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Accounting Speech</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCOUNTING_SPEECH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.StatementImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.CreateTableStatementImpl <em>Create Table Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.CreateTableStatementImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getCreateTableStatement()
   * @generated
   */
  int CREATE_TABLE_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_STATEMENT__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_STATEMENT__COLUMNS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create Table Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.ColumnListImpl <em>Column List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.ColumnListImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getColumnList()
   * @generated
   */
  int COLUMN_LIST = 3;

  /**
   * The feature id for the '<em><b>Column Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_LIST__COLUMN_ITEM = 0;

  /**
   * The number of structural features of the '<em>Column List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.TableImpl <em>Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.TableImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getTable()
   * @generated
   */
  int TABLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.ColumnImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__TYPE = 1;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__TABLE = 2;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectStatementImpl <em>Select Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.SelectStatementImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectStatement()
   * @generated
   */
  int SELECT_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT__TABLES = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT__COLUMNS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT__CONDITION = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Group</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT__GROUP = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Select Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.InsertStatementImpl <em>Insert Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.InsertStatementImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getInsertStatement()
   * @generated
   */
  int INSERT_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_STATEMENT__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_STATEMENT__COLUMNS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_STATEMENT__VALUES = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Insert Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.UpdateStatementImpl <em>Update Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.UpdateStatementImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getUpdateStatement()
   * @generated
   */
  int UPDATE_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_STATEMENT__TABLE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Updates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_STATEMENT__UPDATES = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_STATEMENT__CONDITION = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Update Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.DeleteStatementImpl <em>Delete Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.DeleteStatementImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getDeleteStatement()
   * @generated
   */
  int DELETE_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_STATEMENT__TABLES = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Delete Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELETE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectUpdateListImpl <em>Select Update List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.SelectUpdateListImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectUpdateList()
   * @generated
   */
  int SELECT_UPDATE_LIST = 10;

  /**
   * The feature id for the '<em><b>Update Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_UPDATE_LIST__UPDATE_ITEM = 0;

  /**
   * The number of structural features of the '<em>Select Update List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_UPDATE_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.UpdateItemImpl <em>Update Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.UpdateItemImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getUpdateItem()
   * @generated
   */
  int UPDATE_ITEM = 11;

  /**
   * The feature id for the '<em><b>Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_ITEM__COLUMN = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_ITEM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Update Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATE_ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.InserValuesImpl <em>Inser Values</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.InserValuesImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getInserValues()
   * @generated
   */
  int INSER_VALUES = 12;

  /**
   * The feature id for the '<em><b>Value List</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSER_VALUES__VALUE_LIST = 0;

  /**
   * The number of structural features of the '<em>Inser Values</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSER_VALUES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectTablesListImpl <em>Select Tables List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.SelectTablesListImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectTablesList()
   * @generated
   */
  int SELECT_TABLES_LIST = 13;

  /**
   * The feature id for the '<em><b>Select Table</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TABLES_LIST__SELECT_TABLE = 0;

  /**
   * The number of structural features of the '<em>Select Tables List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TABLES_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectTableImpl <em>Select Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.SelectTableImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectTable()
   * @generated
   */
  int SELECT_TABLE = 14;

  /**
   * The feature id for the '<em><b>Tables</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TABLE__TABLES = DELETE_STATEMENT__TABLES;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TABLE__CONDITION = DELETE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TABLE__TABLE = DELETE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_TABLE_FEATURE_COUNT = DELETE_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectColumnsListImpl <em>Select Columns List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.SelectColumnsListImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectColumnsList()
   * @generated
   */
  int SELECT_COLUMNS_LIST = 15;

  /**
   * The feature id for the '<em><b>Select Column</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COLUMNS_LIST__SELECT_COLUMN = 0;

  /**
   * The number of structural features of the '<em>Select Columns List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_COLUMNS_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.ColumnReferenceImpl <em>Column Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.ColumnReferenceImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getColumnReference()
   * @generated
   */
  int COLUMN_REFERENCE = 16;

  /**
   * The feature id for the '<em><b>Column</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_REFERENCE__COLUMN = 0;

  /**
   * The feature id for the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_REFERENCE__TABLE = 1;

  /**
   * The number of structural features of the '<em>Column Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_REFERENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.LogicExpressionsImpl <em>Logic Expressions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.LogicExpressionsImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getLogicExpressions()
   * @generated
   */
  int LOGIC_EXPRESSIONS = 17;

  /**
   * The number of structural features of the '<em>Logic Expressions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXPRESSIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.ComparisonImpl <em>Comparison</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.ComparisonImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getComparison()
   * @generated
   */
  int COMPARISON = 18;

  /**
   * The feature id for the '<em><b>Left Hand Side</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__LEFT_HAND_SIDE = LOGIC_EXPRESSIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__OPERATOR = LOGIC_EXPRESSIONS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right Hand Side</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON__RIGHT_HAND_SIDE = LOGIC_EXPRESSIONS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Comparison</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_FEATURE_COUNT = LOGIC_EXPRESSIONS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.impl.ConditionImpl
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__LEFT = LOGIC_EXPRESSIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Logic Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__LOGIC_OPERATOR = LOGIC_EXPRESSIONS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__RIGHT = LOGIC_EXPRESSIONS_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = LOGIC_EXPRESSIONS_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.Datatype <em>Datatype</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.Datatype
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 20;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.nlToSql.ComparisonOperatorString <em>Comparison Operator String</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.nlToSql.ComparisonOperatorString
   * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getComparisonOperatorString()
   * @generated
   */
  int COMPARISON_OPERATOR_STRING = 21;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.AccountingSpeech <em>Accounting Speech</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Accounting Speech</em>'.
   * @see uk.ac.kcl.inf.nlToSql.AccountingSpeech
   * @generated
   */
  EClass getAccountingSpeech();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.nlToSql.AccountingSpeech#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.nlToSql.AccountingSpeech#getStatements()
   * @see #getAccountingSpeech()
   * @generated
   */
  EReference getAccountingSpeech_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.CreateTableStatement <em>Create Table Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Table Statement</em>'.
   * @see uk.ac.kcl.inf.nlToSql.CreateTableStatement
   * @generated
   */
  EClass getCreateTableStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.CreateTableStatement#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.CreateTableStatement#getTable()
   * @see #getCreateTableStatement()
   * @generated
   */
  EReference getCreateTableStatement_Table();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.CreateTableStatement#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Columns</em>'.
   * @see uk.ac.kcl.inf.nlToSql.CreateTableStatement#getColumns()
   * @see #getCreateTableStatement()
   * @generated
   */
  EReference getCreateTableStatement_Columns();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.ColumnList <em>Column List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column List</em>'.
   * @see uk.ac.kcl.inf.nlToSql.ColumnList
   * @generated
   */
  EClass getColumnList();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.nlToSql.ColumnList#getColumnItem <em>Column Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Column Item</em>'.
   * @see uk.ac.kcl.inf.nlToSql.ColumnList#getColumnItem()
   * @see #getColumnList()
   * @generated
   */
  EReference getColumnList_ColumnItem();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.Table <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Table
   * @generated
   */
  EClass getTable();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.nlToSql.Table#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Table#getName()
   * @see #getTable()
   * @generated
   */
  EAttribute getTable_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.nlToSql.Column#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Column#getName()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.nlToSql.Column#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Column#getType()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Type();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.nlToSql.Column#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Column#getTable()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Table();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.SelectStatement <em>Select Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Statement</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectStatement
   * @generated
   */
  EClass getSelectStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.SelectStatement#getTables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tables</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectStatement#getTables()
   * @see #getSelectStatement()
   * @generated
   */
  EReference getSelectStatement_Tables();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.SelectStatement#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Columns</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectStatement#getColumns()
   * @see #getSelectStatement()
   * @generated
   */
  EReference getSelectStatement_Columns();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.SelectStatement#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectStatement#getCondition()
   * @see #getSelectStatement()
   * @generated
   */
  EReference getSelectStatement_Condition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.SelectStatement#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Group</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectStatement#getGroup()
   * @see #getSelectStatement()
   * @generated
   */
  EReference getSelectStatement_Group();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.InsertStatement <em>Insert Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Statement</em>'.
   * @see uk.ac.kcl.inf.nlToSql.InsertStatement
   * @generated
   */
  EClass getInsertStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.InsertStatement#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.InsertStatement#getTable()
   * @see #getInsertStatement()
   * @generated
   */
  EReference getInsertStatement_Table();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.InsertStatement#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Columns</em>'.
   * @see uk.ac.kcl.inf.nlToSql.InsertStatement#getColumns()
   * @see #getInsertStatement()
   * @generated
   */
  EReference getInsertStatement_Columns();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.InsertStatement#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Values</em>'.
   * @see uk.ac.kcl.inf.nlToSql.InsertStatement#getValues()
   * @see #getInsertStatement()
   * @generated
   */
  EReference getInsertStatement_Values();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.UpdateStatement <em>Update Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Update Statement</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateStatement
   * @generated
   */
  EClass getUpdateStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.UpdateStatement#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateStatement#getTable()
   * @see #getUpdateStatement()
   * @generated
   */
  EReference getUpdateStatement_Table();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.UpdateStatement#getUpdates <em>Updates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Updates</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateStatement#getUpdates()
   * @see #getUpdateStatement()
   * @generated
   */
  EReference getUpdateStatement_Updates();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.UpdateStatement#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateStatement#getCondition()
   * @see #getUpdateStatement()
   * @generated
   */
  EReference getUpdateStatement_Condition();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.DeleteStatement <em>Delete Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delete Statement</em>'.
   * @see uk.ac.kcl.inf.nlToSql.DeleteStatement
   * @generated
   */
  EClass getDeleteStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.DeleteStatement#getTables <em>Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tables</em>'.
   * @see uk.ac.kcl.inf.nlToSql.DeleteStatement#getTables()
   * @see #getDeleteStatement()
   * @generated
   */
  EReference getDeleteStatement_Tables();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.SelectUpdateList <em>Select Update List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Update List</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectUpdateList
   * @generated
   */
  EClass getSelectUpdateList();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.nlToSql.SelectUpdateList#getUpdateItem <em>Update Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Update Item</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectUpdateList#getUpdateItem()
   * @see #getSelectUpdateList()
   * @generated
   */
  EReference getSelectUpdateList_UpdateItem();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.UpdateItem <em>Update Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Update Item</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateItem
   * @generated
   */
  EClass getUpdateItem();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.UpdateItem#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Column</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateItem#getColumn()
   * @see #getUpdateItem()
   * @generated
   */
  EReference getUpdateItem_Column();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.nlToSql.UpdateItem#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.nlToSql.UpdateItem#getValue()
   * @see #getUpdateItem()
   * @generated
   */
  EAttribute getUpdateItem_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.InserValues <em>Inser Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inser Values</em>'.
   * @see uk.ac.kcl.inf.nlToSql.InserValues
   * @generated
   */
  EClass getInserValues();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.nlToSql.InserValues#getValueList <em>Value List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value List</em>'.
   * @see uk.ac.kcl.inf.nlToSql.InserValues#getValueList()
   * @see #getInserValues()
   * @generated
   */
  EAttribute getInserValues_ValueList();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.SelectTablesList <em>Select Tables List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Tables List</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectTablesList
   * @generated
   */
  EClass getSelectTablesList();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.nlToSql.SelectTablesList#getSelectTable <em>Select Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Select Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectTablesList#getSelectTable()
   * @see #getSelectTablesList()
   * @generated
   */
  EReference getSelectTablesList_SelectTable();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.SelectTable <em>Select Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectTable
   * @generated
   */
  EClass getSelectTable();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.SelectTable#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectTable#getCondition()
   * @see #getSelectTable()
   * @generated
   */
  EReference getSelectTable_Condition();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.nlToSql.SelectTable#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectTable#getTable()
   * @see #getSelectTable()
   * @generated
   */
  EReference getSelectTable_Table();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.SelectColumnsList <em>Select Columns List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Columns List</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectColumnsList
   * @generated
   */
  EClass getSelectColumnsList();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.nlToSql.SelectColumnsList#getSelectColumn <em>Select Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Select Column</em>'.
   * @see uk.ac.kcl.inf.nlToSql.SelectColumnsList#getSelectColumn()
   * @see #getSelectColumnsList()
   * @generated
   */
  EReference getSelectColumnsList_SelectColumn();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.ColumnReference <em>Column Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Reference</em>'.
   * @see uk.ac.kcl.inf.nlToSql.ColumnReference
   * @generated
   */
  EClass getColumnReference();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.nlToSql.ColumnReference#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Column</em>'.
   * @see uk.ac.kcl.inf.nlToSql.ColumnReference#getColumn()
   * @see #getColumnReference()
   * @generated
   */
  EReference getColumnReference_Column();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.nlToSql.ColumnReference#getTable <em>Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Table</em>'.
   * @see uk.ac.kcl.inf.nlToSql.ColumnReference#getTable()
   * @see #getColumnReference()
   * @generated
   */
  EReference getColumnReference_Table();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.LogicExpressions <em>Logic Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Expressions</em>'.
   * @see uk.ac.kcl.inf.nlToSql.LogicExpressions
   * @generated
   */
  EClass getLogicExpressions();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.Comparison <em>Comparison</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Comparison
   * @generated
   */
  EClass getComparison();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.nlToSql.Comparison#getLeftHandSide <em>Left Hand Side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Left Hand Side</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Comparison#getLeftHandSide()
   * @see #getComparison()
   * @generated
   */
  EReference getComparison_LeftHandSide();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.nlToSql.Comparison#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Comparison#getOperator()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_Operator();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.nlToSql.Comparison#getRightHandSide <em>Right Hand Side</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right Hand Side</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Comparison#getRightHandSide()
   * @see #getComparison()
   * @generated
   */
  EAttribute getComparison_RightHandSide();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.nlToSql.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.nlToSql.Condition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Condition#getLeft()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.nlToSql.Condition#getLogicOperator <em>Logic Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Logic Operator</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Condition#getLogicOperator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_LogicOperator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.nlToSql.Condition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Condition#getRight()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Right();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.nlToSql.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Datatype</em>'.
   * @see uk.ac.kcl.inf.nlToSql.Datatype
   * @generated
   */
  EEnum getDatatype();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.nlToSql.ComparisonOperatorString <em>Comparison Operator String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparison Operator String</em>'.
   * @see uk.ac.kcl.inf.nlToSql.ComparisonOperatorString
   * @generated
   */
  EEnum getComparisonOperatorString();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  NlToSqlFactory getNlToSqlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.AccountingSpeechImpl <em>Accounting Speech</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.AccountingSpeechImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getAccountingSpeech()
     * @generated
     */
    EClass ACCOUNTING_SPEECH = eINSTANCE.getAccountingSpeech();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCOUNTING_SPEECH__STATEMENTS = eINSTANCE.getAccountingSpeech_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.StatementImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.CreateTableStatementImpl <em>Create Table Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.CreateTableStatementImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getCreateTableStatement()
     * @generated
     */
    EClass CREATE_TABLE_STATEMENT = eINSTANCE.getCreateTableStatement();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_TABLE_STATEMENT__TABLE = eINSTANCE.getCreateTableStatement_Table();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATE_TABLE_STATEMENT__COLUMNS = eINSTANCE.getCreateTableStatement_Columns();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.ColumnListImpl <em>Column List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.ColumnListImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getColumnList()
     * @generated
     */
    EClass COLUMN_LIST = eINSTANCE.getColumnList();

    /**
     * The meta object literal for the '<em><b>Column Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_LIST__COLUMN_ITEM = eINSTANCE.getColumnList_ColumnItem();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.TableImpl <em>Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.TableImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getTable()
     * @generated
     */
    EClass TABLE = eINSTANCE.getTable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE__NAME = eINSTANCE.getTable_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.ColumnImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__NAME = eINSTANCE.getColumn_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__TYPE = eINSTANCE.getColumn_Type();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__TABLE = eINSTANCE.getColumn_Table();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectStatementImpl <em>Select Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.SelectStatementImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectStatement()
     * @generated
     */
    EClass SELECT_STATEMENT = eINSTANCE.getSelectStatement();

    /**
     * The meta object literal for the '<em><b>Tables</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_STATEMENT__TABLES = eINSTANCE.getSelectStatement_Tables();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_STATEMENT__COLUMNS = eINSTANCE.getSelectStatement_Columns();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_STATEMENT__CONDITION = eINSTANCE.getSelectStatement_Condition();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_STATEMENT__GROUP = eINSTANCE.getSelectStatement_Group();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.InsertStatementImpl <em>Insert Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.InsertStatementImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getInsertStatement()
     * @generated
     */
    EClass INSERT_STATEMENT = eINSTANCE.getInsertStatement();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_STATEMENT__TABLE = eINSTANCE.getInsertStatement_Table();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_STATEMENT__COLUMNS = eINSTANCE.getInsertStatement_Columns();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_STATEMENT__VALUES = eINSTANCE.getInsertStatement_Values();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.UpdateStatementImpl <em>Update Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.UpdateStatementImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getUpdateStatement()
     * @generated
     */
    EClass UPDATE_STATEMENT = eINSTANCE.getUpdateStatement();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE_STATEMENT__TABLE = eINSTANCE.getUpdateStatement_Table();

    /**
     * The meta object literal for the '<em><b>Updates</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE_STATEMENT__UPDATES = eINSTANCE.getUpdateStatement_Updates();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE_STATEMENT__CONDITION = eINSTANCE.getUpdateStatement_Condition();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.DeleteStatementImpl <em>Delete Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.DeleteStatementImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getDeleteStatement()
     * @generated
     */
    EClass DELETE_STATEMENT = eINSTANCE.getDeleteStatement();

    /**
     * The meta object literal for the '<em><b>Tables</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DELETE_STATEMENT__TABLES = eINSTANCE.getDeleteStatement_Tables();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectUpdateListImpl <em>Select Update List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.SelectUpdateListImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectUpdateList()
     * @generated
     */
    EClass SELECT_UPDATE_LIST = eINSTANCE.getSelectUpdateList();

    /**
     * The meta object literal for the '<em><b>Update Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_UPDATE_LIST__UPDATE_ITEM = eINSTANCE.getSelectUpdateList_UpdateItem();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.UpdateItemImpl <em>Update Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.UpdateItemImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getUpdateItem()
     * @generated
     */
    EClass UPDATE_ITEM = eINSTANCE.getUpdateItem();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UPDATE_ITEM__COLUMN = eINSTANCE.getUpdateItem_Column();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATE_ITEM__VALUE = eINSTANCE.getUpdateItem_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.InserValuesImpl <em>Inser Values</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.InserValuesImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getInserValues()
     * @generated
     */
    EClass INSER_VALUES = eINSTANCE.getInserValues();

    /**
     * The meta object literal for the '<em><b>Value List</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSER_VALUES__VALUE_LIST = eINSTANCE.getInserValues_ValueList();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectTablesListImpl <em>Select Tables List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.SelectTablesListImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectTablesList()
     * @generated
     */
    EClass SELECT_TABLES_LIST = eINSTANCE.getSelectTablesList();

    /**
     * The meta object literal for the '<em><b>Select Table</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_TABLES_LIST__SELECT_TABLE = eINSTANCE.getSelectTablesList_SelectTable();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectTableImpl <em>Select Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.SelectTableImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectTable()
     * @generated
     */
    EClass SELECT_TABLE = eINSTANCE.getSelectTable();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_TABLE__CONDITION = eINSTANCE.getSelectTable_Condition();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_TABLE__TABLE = eINSTANCE.getSelectTable_Table();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.SelectColumnsListImpl <em>Select Columns List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.SelectColumnsListImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getSelectColumnsList()
     * @generated
     */
    EClass SELECT_COLUMNS_LIST = eINSTANCE.getSelectColumnsList();

    /**
     * The meta object literal for the '<em><b>Select Column</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT_COLUMNS_LIST__SELECT_COLUMN = eINSTANCE.getSelectColumnsList_SelectColumn();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.ColumnReferenceImpl <em>Column Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.ColumnReferenceImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getColumnReference()
     * @generated
     */
    EClass COLUMN_REFERENCE = eINSTANCE.getColumnReference();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_REFERENCE__COLUMN = eINSTANCE.getColumnReference_Column();

    /**
     * The meta object literal for the '<em><b>Table</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_REFERENCE__TABLE = eINSTANCE.getColumnReference_Table();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.LogicExpressionsImpl <em>Logic Expressions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.LogicExpressionsImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getLogicExpressions()
     * @generated
     */
    EClass LOGIC_EXPRESSIONS = eINSTANCE.getLogicExpressions();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.ComparisonImpl <em>Comparison</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.ComparisonImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getComparison()
     * @generated
     */
    EClass COMPARISON = eINSTANCE.getComparison();

    /**
     * The meta object literal for the '<em><b>Left Hand Side</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON__LEFT_HAND_SIDE = eINSTANCE.getComparison_LeftHandSide();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__OPERATOR = eINSTANCE.getComparison_Operator();

    /**
     * The meta object literal for the '<em><b>Right Hand Side</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON__RIGHT_HAND_SIDE = eINSTANCE.getComparison_RightHandSide();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.impl.ConditionImpl
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__LEFT = eINSTANCE.getCondition_Left();

    /**
     * The meta object literal for the '<em><b>Logic Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__LOGIC_OPERATOR = eINSTANCE.getCondition_LogicOperator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__RIGHT = eINSTANCE.getCondition_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.Datatype <em>Datatype</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.Datatype
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getDatatype()
     * @generated
     */
    EEnum DATATYPE = eINSTANCE.getDatatype();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.nlToSql.ComparisonOperatorString <em>Comparison Operator String</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.nlToSql.ComparisonOperatorString
     * @see uk.ac.kcl.inf.nlToSql.impl.NlToSqlPackageImpl#getComparisonOperatorString()
     * @generated
     */
    EEnum COMPARISON_OPERATOR_STRING = eINSTANCE.getComparisonOperatorString();

  }

} //NlToSqlPackage
