/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getSelectStatement()
 * @model
 * @generated
 */
public interface SelectStatement extends Statement
{
} // SelectStatement
