/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.nlToSql;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Update Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.nlToSql.NlToSqlPackage#getUpdateStatement()
 * @model
 * @generated
 */
public interface UpdateStatement extends Statement
{
} // UpdateStatement
