/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NlToSqlStandaloneSetup extends NlToSqlStandaloneSetupGenerated {

	public static void doSetup() {
		new NlToSqlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
